### ISSUE TITLE
Support for import and export setting

### ISSUE THREAD

**Issue by AustinGil** [iduspara/codeimg_feedback#1]
Hey, nice work on this tool. It works great.
I've used Now's Carbon tool for something similar, but I think I like this one better. The one piece of advice I could think of to make it better is the support to save the settings that I choose. 

With Carbon, I can configure some settings and save them as a template (presumably store in local storage). It's nice because I use a lot of the same settings over and over.

Another thing Carbon does is update the URL query parameters with all the settings and the content so I can share that URL with someone else and they will see the same thing.

Lastly, I saw the ToDo list and would definitely +1 the VS Code plugin :)

Overall, very happy with it. Nice work.

**Comment by iduspara** [comment]
Hey, i added this as a Feature request to our ToDo list.

**Comment by iduspara** [comment]
The Settings are now stored in LocalStorage
